import {getServerUrl} from '@/config/server-config';
import * as FileSystem from 'expo-file-system/legacy';
import JSZip from 'jszip';
import type { EmbeddingStatus } from './embedding';
export type ModelManifest={id:string;version:string;runtime:'litert'|'onnx';format:'task'|'tflite'|'onnx';archive:string;archiveBytes:number;extractedBytes:number;entryPoint:string;sha256?:string;mock?:boolean};
const ROOT=`${FileSystem.documentDirectory}models/`;
export function validateManifest(value:unknown):value is ModelManifest{if(!value||typeof value!=='object')return false;const m=value as Record<string,unknown>;return typeof m.id==='string'&&typeof m.version==='string'&&typeof m.archive==='string'&&m.archive.endsWith('.zip')&&typeof m.archiveBytes==='number'&&m.archiveBytes>0&&typeof m.entryPoint==='string'&&!m.entryPoint.includes('..')}
async function fetchManifest(){const response=await fetch(`${getServerUrl()}/models/embeddinggemma/manifest.json`);if(!response.ok)throw Error(`Manifest request failed (${response.status})`);const manifest:unknown=await response.json();if(!validateManifest(manifest))throw Error('Invalid model manifest');return manifest}
const installDir=(m:ModelManifest)=>`${ROOT}${m.id.replace(/[^a-z0-9_-]/gi,'_')}-${m.version}/`,entryPath=(m:ModelManifest)=>installDir(m)+m.entryPoint;
export async function getModelState():Promise<{status:EmbeddingStatus;path?:string;manifest?:ModelManifest}>{try{const manifest=await fetchManifest(),path=entryPath(manifest),info=await FileSystem.getInfoAsync(path);return info.exists?{status:readyStatus(manifest),path,manifest}:{status:{kind:'missing',progress:0,label:`Download ${formatBytes(manifest.archiveBytes)} ZIP`},manifest}}catch{return{status:{kind:'missing',progress:0,label:'Model server unavailable'}}}}
export async function downloadModel(onProgress:(s:EmbeddingStatus)=>void){const manifest=await fetchManifest();await FileSystem.makeDirectoryAsync(ROOT,{intermediates:true});const directory=installDir(manifest);await FileSystem.makeDirectoryAsync(directory,{intermediates:true});const archivePath=`${ROOT}${manifest.archive}`,task=FileSystem.createDownloadResumable(`${getServerUrl()}/models/embeddinggemma/${manifest.archive}`,archivePath,{},p=>{const progress=p.totalBytesWritten/Math.max(p.totalBytesExpectedToWrite,1);onProgress({kind:'downloading',progress:progress*.8,label:`Downloading ZIP ${Math.round(progress*100)}%`})}),result=await task.downloadAsync();if(!result)throw Error('Download interrupted');onProgress({kind:'downloading',progress:.82,label:'Unpacking model…'});await extractZip(result.uri,directory,p=>onProgress({kind:'downloading',progress:.8+p*.2,label:`Unpacking ${Math.round(p*100)}%`}));await FileSystem.deleteAsync(result.uri,{idempotent:true});const path=entryPath(manifest);if(!(await FileSystem.getInfoAsync(path)).exists)throw Error(`ZIP did not contain ${manifest.entryPoint}`);onProgress(readyStatus(manifest));return{path,manifest}}
async function extractZip(uri:string,destination:string,progress:(value:number)=>void){const base64=await FileSystem.readAsStringAsync(uri,{encoding:FileSystem.EncodingType.Base64}),zip=await JSZip.loadAsync(base64,{base64:true,checkCRC32:true}),files=Object.values(zip.files).filter(file=>!file.dir);for(let index=0;index<files.length;index++){const file=files[index],safeName=file.name.replace(/\\/g,'/');if(safeName.startsWith('/')||safeName.split('/').includes('..'))throw Error('Unsafe ZIP entry');const target=destination+safeName,parent=target.slice(0,target.lastIndexOf('/')+1);await FileSystem.makeDirectoryAsync(parent,{intermediates:true});await FileSystem.writeAsStringAsync(target,await file.async('base64'),{encoding:FileSystem.EncodingType.Base64});progress((index+1)/Math.max(files.length,1))}}
function readyStatus(manifest:ModelManifest):EmbeddingStatus{return{kind:manifest.mock?'fallback':'ready',progress:1,label:manifest.mock?'Mock model ready · ZIP unpacked':'EmbeddingGemma ready'}}
function formatBytes(n:number){return n>1e6?`${(n/1e6).toFixed(0)} MB`:`${Math.ceil(n/1024)} KB`}
