import {describe,expect,it,jest,beforeEach} from '@jest/globals';
import {QuestionBankAgent} from '../ai/agent';
import {HashEmbeddingProvider} from '../ai/embeddings/embedding';
import {SEED_QUESTIONS} from '../data/questions';
import type {ChatModel,GenerationOptions,TutorTurn} from '../ai/chat-model';
import * as database from '../db/database';
jest.mock('../db/database',()=>({getQuestions:jest.fn(),getQuestion:jest.fn(),getEmbedding:jest.fn(),saveEmbedding:jest.fn()}));
const mocked=database as jest.Mocked<typeof database>;
class ScriptedModel implements ChatModel{readonly name='scripted';calls:{turns:TutorTurn[];options?:GenerationOptions}[]=[];constructor(private outputs:string[]){}async initialize(){}async generate(turns:TutorTurn[],onToken?:(token:string)=>void,options?:GenerationOptions){this.calls.push({turns,options});const output=this.outputs.shift()||'';onToken?.(output);return output}}
describe('model-routed tutor smoke test',()=>{beforeEach(()=>{jest.clearAllMocks();mocked.getQuestions.mockResolvedValue(SEED_QUESTIONS);mocked.getQuestion.mockImplementation(async(_db:any,id:string)=>SEED_QUESTIONS.find(q=>q.id===id));mocked.getEmbedding.mockResolvedValue(null);mocked.saveEmbedding.mockResolvedValue(undefined)});
 it('keeps ordinary conversation out of database tools',async()=>{const router=new ScriptedModel(['{"mode":"chat"}']),chat=new ScriptedModel(['I am your local exam tutor.']),agent=new QuestionBankAgent({} as any,new HashEmbeddingProvider(),chat,router);const reply=await agent.invoke({message:'Who are you?',context:{}});expect(reply.content).toContain('local exam tutor');expect(reply.toolCalls).toHaveLength(0);expect(mocked.getQuestions).not.toHaveBeenCalled();expect(router.calls[0].options?.jsonSchema).toBeDefined()});
 it('lists a filtered year with pagination and grounds the final prompt',async()=>{const router=new ScriptedModel(['{"mode":"tool","tool":"listQuestions","arguments":{"year":2024,"page":1,"pageSize":2},"goal":"list 2024 questions"}']),chat=new ScriptedModel(['Page 1 of 3 - 5 total']),agent=new QuestionBankAgent({} as any,new HashEmbeddingProvider(),chat,router);const reply=await agent.invoke({message:'Show all 2024 questions',context:{}});expect(reply.toolCalls[0].name).toBe('list_exam_questions');expect(reply.toolCalls[0].resultCount).toBe(2);expect(reply.context.page).toBe(1);expect(reply.context.pageSize).toBe(2);expect(chat.calls[0].turns.at(-1)?.content).toContain('"total":5');expect(reply.suggestions).toContain('Next page')});
 it('uses EmbeddingGemma only inside semantic search',async()=>{const embeddings=new HashEmbeddingProvider(),embedSpy=jest.spyOn(embeddings,'embedQuery'),router=new ScriptedModel(['{"mode":"tool","tool":"retrieveQuestions","arguments":{"query":"water through membrane","page":1,"pageSize":3}}']),chat=new ScriptedModel(['I found the stored osmosis question.']),agent=new QuestionBankAgent({} as any,embeddings,chat,router);const reply=await agent.invoke({message:'Find the question about water moving through a membrane',context:{}});expect(embedSpy).toHaveBeenCalledWith('water through membrane');expect(reply.toolCalls[0].name).toBe('search_exam_questions');expect(chat.calls[0].turns.at(-1)?.content).toContain('TOOL OUTPUT')});
});
