import type {SQLiteDatabase} from 'expo-sqlite';
import type {AgentContext,AgentReply,ToolTrace} from '@/domain/types';
import type {EmbeddingProvider} from '@/ai/embeddings/embedding';
import type {ChatModel} from './chat-model';
import {createQuestionTools} from './tools';
type Input={message:string;context:AgentContext;fullExplanation?:boolean};
type Plan={mode:'chat'|'tool';tool?:'listQuestions'|'retrieveQuestions'|'getQuestionDetails'|'inspectCatalogue';arguments?:Record<string,unknown>;goal?:string};
const PLAN_SCHEMA={type:'object',additionalProperties:false,required:['mode'],properties:{mode:{type:'string',enum:['chat','tool']},tool:{type:'string',enum:['listQuestions','retrieveQuestions','getQuestionDetails','inspectCatalogue']},arguments:{type:'object'},goal:{type:'string'}}};
const TOOL_GUIDE=`Available tools:\n1. listQuestions(category?,subject?,topic?,year?,paper?,page,pageSize): exhaustive filtered listing.\n2. retrieveQuestions(query,category?,subject?,topic?,year?,paper?,page,pageSize): semantic search.\n3. getQuestionDetails(id): exact question, answer, hints and solution.\n4. inspectCatalogue(category?,subject?,year?): availability and counts.\nReturn JSON only: {"mode":"chat"} for ordinary conversation, or {"mode":"tool","tool":"listQuestions","arguments":{...},"goal":"..."}. Never call a tool for greetings, identity, study advice, or casual conversation. Use listQuestions for all questions in a paper/year/topic and pagination. Use retrieveQuestions for concepts or partial wording. Preserve filters and increment page for next-page requests.`;
export class QuestionBankAgent{private tools;constructor(db:SQLiteDatabase,embeddings:EmbeddingProvider,private chat:ChatModel,private router:ChatModel=chat){this.tools=createQuestionTools(db,embeddings)}
 async invoke(input:Input,onToken?:(token:string)=>void):Promise<AgentReply>{const plan=await this.plan(input),traces:ToolTrace[]=[];if(plan.mode==='chat')return this.chatReply(input,traces,onToken);const key=plan.tool&&plan.tool in this.tools?plan.tool:undefined;if(!key)return this.chatReply(input,traces,onToken);const selected:any=this.tools[key],args={...(plan.arguments||{})};const value=await selected.invoke(args);traces.push({name:selected.name,input:args,resultCount:Array.isArray(value)?value.length:Array.isArray(value?.items)?value.items.length:value?.count});const context=this.nextContext(input.context,key,args,value);const content=await this.chat.generate([{role:'system',content:`You are QuestionBank Tutor, an expert Cameroon GCE tutor. The tool output below is the only authority for exam questions, answers, solutions, availability, counts, years, papers, and topics. Never invent or alter those facts. Respond naturally to the student's actual request. For a list, show every item in the returned page with question number, source, topic, and question text; state "Page X of Y - N total"" and offer next/previous navigation. For an explanation, teach step by step using the stored answer and solution, preserving Markdown and LaTeX. If the tool found nothing, say so plainly and suggest broader filters. Do not mention internal routing or claim a strong match.`},{role:'user',content:`STUDENT: ${input.message}\nGOAL: ${plan.goal||'Answer the request'}\nTOOL: ${selected.name}\nTOOL OUTPUT:\n${JSON.stringify(value)}`}],onToken);return{content:content||'I could not produce a grounded response from the returned database records.',context,toolCalls:traces,suggestions:this.suggestions(value)}}
 private async plan(input:Input):Promise<Plan>{const raw=await this.router.generate([{role:'system',content:`You are the private tool-routing model for a local exam tutor. ${TOOL_GUIDE}`},{role:'user',content:`Conversation state: ${JSON.stringify(input.context)}\nStudent message: ${input.message}`}],undefined,{jsonSchema:PLAN_SCHEMA,maxTokens:180,temperature:0});try{const start=raw.indexOf('{'),end=raw.lastIndexOf('}');if(start<0||end<start)return{mode:'chat'};const plan=JSON.parse(raw.slice(start,end+1));return plan?.mode==='tool'?plan:{mode:'chat'}}catch{return{mode:'chat'}}}
 private async chatReply(input:Input,traces:ToolTrace[],onToken?:(token:string)=>void):Promise<AgentReply>{const content=await this.chat.generate([{role:'system',content:'You are QuestionBank Tutor, a warm, concise, expert study companion. Converse naturally. Explain your role and study methods freely, but never invent database contents or past-exam facts. When the student asks for exam-specific material, encourage a precise subject, year, paper, or topic request.'},{role:'user',content:input.message}],onToken);return{content,context:input.context,toolCalls:traces,suggestions:['Browse a paper','Find a topic','Help me revise']}}
 private nextContext(current:AgentContext,key:string,args:Record<string,unknown>,value:any):AgentContext{const first=value?.items?.[0]||value;return{...current,category:(args.category||first?.category||current.category) as any,subject:(args.subject||first?.subject||current.subject) as any,topic:(args.topic||first?.topic||current.topic) as any,year:(args.year||first?.year||current.year) as any,activeQuestionId:first?.id||current.activeQuestionId,page:Number(value?.page||args.page||1),pageSize:Number(value?.pageSize||args.pageSize||5),lastTool:key,lastArguments:args}}
 private suggestions(value:any){const out:string[]=[];if(value?.page>1)out.push('Previous page');if(value?.page<value?.totalPages)out.push('Next page');out.push('Explain one of these','Change the filters');return out}
}
