export type QueryIntent='identity'|'capabilities'|'greeting'|'thanks'|'list'|'next_page'|'previous_page'|'hint'|'explain'|'similar'|'academic'|'conversation';
export type QueryPlan={intent:QueryIntent;year?:number;paper?:number;category?:'OL'|'AL';subject?:string;topic?:string};
const subjects=[['Mathematics',['mathematics','maths','math']],['Physics',['physics','physic']],['Chemistry',['chemistry','chem']],['Biology',['biology','bio']],['English Language',['english']]] as const;
const topics=['Algebra','Geometry','Calculus','Mechanics','Mole Concept','Cell Biology','Osmosis'];
const lists=new Set(['all','list','show','give','return','display','available','every']);
export function planQuery(input:string):QueryPlan{const words=tokenize(input),phrase=words.join(' '),year=words.map(Number).find(n=>n>=2000&&n<=2099),paperAt=words.indexOf('paper'),paper=paperAt>=0?toSmallNumber(words[paperAt+1]):undefined,category=hasAny(words,['ordinary','ol'])?'OL':hasAny(words,['advanced','al'])?'AL':undefined,subject=subjects.find(([,aliases])=>aliases.some(alias=>words.some(word=>similar(word,alias))))?.[0],topic=topics.find(value=>value.toLowerCase().split(' ').every(part=>words.some(word=>similar(word,part))));const filters={year,paper,category:category as 'OL'|'AL'|undefined,subject,topic};if(startsWithAny(phrase,['who are you','what are you']))return{intent:'identity',...filters};if(startsWithAny(phrase,['what do you do','what can you do','how can you help']))return{intent:'capabilities',...filters};if(words.length<=4&&hasAny(words,['hello','hi','hey']))return{intent:'greeting',...filters};if(hasAny(words,['thanks','thank','thx']))return{intent:'thanks',...filters};if(startsWithAny(phrase,['next page','show more','more results']))return{intent:'next_page',...filters};if(startsWithAny(phrase,['previous page','prev page','go back']))return{intent:'previous_page',...filters};if(hasAny(words,['hint','clue','stuck']))return{intent:'hint',...filters};if(hasAny(words,['explain','solution','solve','why','answer','further','deeper']))return{intent:'explain',...filters};if(hasAny(words,['similar','another'])&&hasAny(words,['question','one','practice']))return{intent:'similar',...filters};if(words.some(word=>lists.has(word))&&(hasAny(words,['question','questions','paper','year','topic','subject'])||!!year||!!paper||!!topic||!!subject))return{intent:'list',...filters};if(!!year||!!paper||!!topic||!!subject||hasAny(words,['exam','question','gce','study','revision']))return{intent:'academic',...filters};return{intent:'conversation',...filters}}
function tokenize(value:string){return value.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,' ').trim().split(' ').filter(Boolean)}
function hasAny(words:string[],values:string[]){return values.some(value=>words.includes(value))}
function startsWithAny(phrase:string,values:string[]){return values.some(value=>phrase.startsWith(value))}
function toSmallNumber(value?:string){const names:Record<string,number>={one:1,two:2,three:3};const number=Number(value);return number>=1&&number<=3?number:names[value||'']}
function similar(a:string,b:string){if(a===b)return true;if(Math.abs(a.length-b.length)>2)return false;let previous=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const current=[i];for(let j=1;j<=b.length;j++)current[j]=Math.min(current[j-1]+1,previous[j]+1,previous[j-1]+(a[i-1]===b[j-1]?0:1));previous=current}return previous[b.length]<=Math.max(1,Math.floor(Math.max(a.length,b.length)*.25))}
