import {tool} from '@langchain/core/tools';
import {z} from 'zod';
import type {SQLiteDatabase} from 'expo-sqlite';
import {cosine,type EmbeddingProvider} from '@/ai/embeddings/embedding';
import {getEmbedding,getQuestion,getQuestions,saveEmbedding} from '@/db/database';
const filters=z.object({category:z.enum(['OL','AL']).optional(),subject:z.string().optional(),topic:z.string().optional(),year:z.number().optional(),paper:z.number().min(1).max(3).optional(),page:z.number().min(1).default(1),pageSize:z.number().min(1).max(10).default(5)});
export function createQuestionTools(db:SQLiteDatabase,embeddings:EmbeddingProvider){
 const listQuestions=tool(async(input)=>{const all=await getQuestions(db),rows=all.filter(q=>(!input.category||q.category===input.category)&&(!input.subject||q.subject.toLowerCase().includes(input.subject.toLowerCase()))&&(!input.topic||q.topic.toLowerCase().includes(input.topic.toLowerCase()))&&(!input.year||q.year===input.year)&&(!input.paper||q.paper===input.paper)).sort((a,b)=>a.number-b.number),start=(input.page-1)*input.pageSize;return{items:rows.slice(start,start+input.pageSize),total:rows.length,page:input.page,pageSize:input.pageSize,totalPages:Math.max(1,Math.ceil(rows.length/input.pageSize))}},{name:'list_exam_questions',description:'List every matching exam question by level, subject, topic, year, and paper with UI pagination. Use this for all/list/show/browse requests and next or previous pages.',schema:filters});
 const retrieveQuestions=tool(async(input)=>{const all=await getQuestions(db),queryVector=await embeddings.embedQuery(input.query),ranked=[] as {question:any;score:number}[];for(const q of all){if(input.category&&q.category!==input.category)continue;if(input.subject&&!q.subject.toLowerCase().includes(input.subject.toLowerCase()))continue;if(input.topic&&!q.topic.toLowerCase().includes(input.topic.toLowerCase()))continue;if(input.year&&q.year!==input.year)continue;if(input.paper&&q.paper!==input.paper)continue;let vector=await getEmbedding(db,q.id);if(!vector){vector=(await embeddings.embedDocuments([`${q.markdown}\nTopic: ${q.topic}\nTags: ${q.tags.join(', ')}`],[`${q.subject} ${q.year} Paper ${q.paper}`]))[0];await saveEmbedding(db,q.id,vector)}ranked.push({question:q,score:cosine(queryVector,vector)})}ranked.sort((a,b)=>b.score-a.score);const start=(input.page-1)*input.pageSize;return{items:ranked.slice(start,start+input.pageSize).map(x=>({...x.question,score:Number(x.score.toFixed(3))})),total:ranked.length,page:input.page,pageSize:input.pageSize,totalPages:Math.max(1,Math.ceil(ranked.length/input.pageSize))}},{name:'search_exam_questions',description:'Semantic RAG search for a concept, remembered wording, or misspelled text. Returns paginated database records.',schema:filters.extend({query:z.string()})});
 const getQuestionDetails=tool(async({id})=>getQuestion(db,id),{name:'get_question_details',description:'Load one exact stored question with its answer, hints, and authored solution.',schema:z.object({id:z.string()})});
 const inspectCatalogue=tool(async(input)=>{const all=await getQuestions(db),rows=all.filter(q=>(!input.category||q.category===input.category)&&(!input.subject||q.subject.toLowerCase().includes(input.subject.toLowerCase()))&&(!input.year||q.year===input.year));return{count:rows.length,subjects:[...new Set(rows.map(q=>q.subject))],topics:[...new Set(rows.map(q=>q.topic))],years:[...new Set(rows.map(q=>q.year))].sort(),papers:[...new Set(rows.map(q=>`${q.year} ${q.category} ${q.subject} Paper ${q.paper}`))]}} ,{name:'inspect_exam_catalogue',description:'Check what subjects, topics, years, and papers exist in the local database.',schema:z.object({category:z.enum(['OL','AL']).optional(),subject:z.string().optional(),year:z.number().optional()})});
 return{listQuestions,retrieveQuestions,getQuestionDetails,inspectCatalogue};
}
